language: python
python:
    - 3.6
install:
    - sudo apt update -y
    - sudo apt install -y build-essential python3-dev libgmp-dev libmpfr-dev libmpc-dev
    - pip install gmpy2 numpy
script:
    - [ $(python a.py -a ABCDEFGHIJKLMNOPQRSTUVWXYZ -k GYBNQKURP encrypt CAT) = FIN ]
    - [ $(python a.py -a ABCDEFGHIJKLMNOPQRSTUVWXYZ -k GYBNQKURP decrypt FIN) = CAT ]
