language: python
python:
    - 3.6
install:
    - pip install gmpy2 numpy
script:
    - [ $(python a.py -a ABCDEFGHIJKLMNOPQRSTUVWXYZ -k GYBNQKURP encrypt CAT) = FIN ]
    - [ $(python a.py -a ABCDEFGHIJKLMNOPQRSTUVWXYZ -k GYBNQKURP decrypt FIN) = CAT ]
